name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd server
        npm ci
        cd ../client
        npm ci
    
    - name: Run tests
      run: |
        cd server
        npm test
        cd ../client
        npm test
    
    - name: Build
      run: |
        cd server
        npm run build
        cd ../client
        npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd server
        npm ci
        cd ../client
        npm ci
    
    - name: Run linter
      run: |
        cd server
        npm run lint
        cd ../client
        npm run lint

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd server
        npm ci
        cd ../client
        npm ci
    
    - name: Run security audit
      run: |
        cd server
        npm audit
        cd ../client
        npm audit 